### PR TITLE
Add visible element to squares

### PR DESCRIPTION
**Pull request by osu-murphcol**

### CODE REVIEW

**Comment by evanmhm** [comment]
Just finished the sonar function, we need to implement checks so you can't sonar again until you've sunk a ship. This should be merged and a separate issue created for that feature.

**Comment by evanmhm** [comment]
Resolves issue #49

**Comment by osu-murphcol** [comment]
Very nice, now we just have to make the color scheme match the requirements. This should be merged.

**Review by roy017 — APPROVED** [review]
Looks good, Sonar code looks correct, just have to adjust colors to expected format.

**Pull request merged**
